{
 "title": "Kopia",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Host: ",
    "query": {
     "query": "label_values(kopia_blob_errors_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kopia_cache_store_errors_total{instance=~\"$server:.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Cache store errors"
    },
    {
     "expr": "sum(rate(kopia_cache_miss_errors_total{instance=~\"$server:.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Cache miss errors"
    },
    {
     "expr": "sum(rate(kopia_blob_errors_total{instance=~\"$server:.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Blob errors"
    },
    {
     "expr": "sum(rate(kopia_content_get_not_found_count_total{instance=~\"$server:.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Not found"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kopia_cache_hit_total{instance=~\"$server:.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(rate(kopia_cache_miss_total{instance=~\"$server:.*\"}[$__rate_interval]) * -1) by (instance)",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Uploaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(kopia_content_uploaded_bytes_total{instance=~\"$server:.*\"}[$__rate_interval]) / 1024 / 1024",
     "legendFormat": "Uploaded"
    },
    {
     "expr": "rate(kopia_content_compression_attempted_bytes_total{instance=~\"$server:.*\"}[$__rate_interval]) / 1024 / 1024",
     "legendFormat": "Compressed"
    },
    {
     "expr": "rate(kopia_content_non_compressible_bytes_total{instance=~\"$server:.*\"}[$__rate_interval]) / 1024 / 1024",
     "legendFormat": "Non compressed"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(kopia_blob_download_full_blob_bytes_total{instance=~\"$server:.*\"}[$__rate_interval])",
     "legendFormat": "Full blob"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kopia_blob_storage_latency_ms_sum{instance=~\"$server:.*\"}[$__rate_interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}